{"name": "Locked-Out User Login Test", "status": "passed", "description": "This test verifies that attempting to log in with the locked-out user credentials ('locked_out_user') displays the correct error message and prevents login.", "attachments": [{"name": "stdout", "source": "4246a988-fa88-4370-b4e0-30e0ea6abf99-attachment.txt", "type": "text/plain"}], "start": 1736339416149, "stop": 1736339416509, "uuid": "49349c45-9fa8-4292-b2ba-be7d6bd97d7c", "historyId": "8d1cb9a30e257ed76459024d9baf3600", "testCaseId": "8d1cb9a30e257ed76459024d9baf3600", "fullName": "tests.login_test.TestLogin#test_04_login_locked_out_user", "labels": [{"name": "tag", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Assaf"}, {"name": "thread", "value": "6580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}