{"name": "Invalid Username Login Test", "status": "passed", "description": "This test verifies that attempting to log in with an incorrect username ('standad_usr') displays the correct error message and prevents login.", "start": 1736339384150, "stop": 1736339384505, "uuid": "35a00d21-20ec-4357-adf9-0dd380210258", "historyId": "29f8ba292d2ff0986f04d062e1d84ead", "testCaseId": "29f8ba292d2ff0986f04d062e1d84ead", "fullName": "tests.login_test.TestLogin#test_02_invalid_username_standard_user", "labels": [{"name": "tag", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Assaf"}, {"name": "thread", "value": "2148-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}